-- Squirrel — the whole schema, in one script.
--
-- Generated by `npm run schema:bundle` from supabase/migrations/. Paste this
-- into the Supabase SQL editor of a NEW project and the database is ready:
-- tables, row-level security, the plan limits that actually enforce the tiers,
-- sync, billing, and calendar links.
--
-- First run only. This creates tables and types, so running it against a
-- database that already has them fails — the guard below says so in one
-- sentence rather than leaving you to read a wall of "already exists". To
-- apply a later change to a live database, run that numbered migration alone.
--
-- Do not edit this file — it is regenerated. Change the numbered migration.

do $$
begin
  if exists (select 1 from information_schema.tables
             where table_schema = 'public' and table_name = 'profiles') then
    raise exception
      'Squirrel schema is already installed. Run the individual migration you need from supabase/migrations/ instead of this bundle.';
  end if;
end $$;


-- ======================================================================
-- 0001_init.sql
-- ======================================================================

-- Squirrel — initial schema.
--
-- Every table is row-level-secured to the owning user. The client talks to
-- Postgres directly with the anon key, so RLS is the only thing standing
-- between one customer's data and another's — there is no server in that path
-- to check on its behalf.
--
-- Plan limits are enforced by database triggers rather than in the client, for
-- the same reason: anything the client enforces is a suggestion.

create extension if not exists "uuid-ossp";

-- ---------------------------------------------------------------- profiles
create type plan_tier as enum ('free', 'plus', 'pro');

create table profiles (
  id                     uuid primary key references auth.users on delete cascade,
  email                  text,
  phone                  text,
  full_name              text,
  plan                   plan_tier not null default 'free',
  -- Billing state is written only by the Stripe webhook (service role).
  stripe_customer_id     text unique,
  stripe_subscription_id text unique,
  plan_renews_at         timestamptz,
  -- Set when an Apple IAP receipt grants the plan instead of Stripe.
  apple_transaction_id   text unique,
  created_at             timestamptz not null default now()
);

alter table profiles enable row level security;

create policy "own profile read"   on profiles for select using (auth.uid() = id);
create policy "own profile update" on profiles for update using (auth.uid() = id)
  -- Plan and billing columns are deliberately not writable here; the webhook
  -- uses the service role, which bypasses RLS.
  with check (auth.uid() = id);

create function handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name')
  on conflict (id) do nothing;
  return new;
end $$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ---------------------------------------------------------------- projects
create table projects (
  id         uuid primary key default uuid_generate_v4(),
  user_id    uuid not null references auth.users on delete cascade,
  name       text not null,
  client     text default '',
  value      numeric,
  status     text not null default 'active',
  archived   boolean not null default false,
  created_at timestamptz not null default now()
);

create index projects_user_idx on projects (user_id) where not archived;

-- ------------------------------------------------------------------- tasks
create table tasks (
  id            uuid primary key default uuid_generate_v4(),
  user_id       uuid not null references auth.users on delete cascade,
  project_id    uuid references projects on delete cascade,
  title         text not null,
  notes         text default '',
  estimate_mins integer not null default 30,
  due           date,
  priority      text not null default 'normal'
                check (priority in ('critical', 'high', 'normal', 'low')),
  delegated_to  text default '',
  done          boolean not null default false,
  done_at       timestamptz,
  scheduled_for date,
  sort_order    integer,
  created_at    timestamptz not null default now()
);

create index tasks_user_open_idx on tasks (user_id, due) where not done;
create index tasks_project_idx on tasks (project_id);

-- ------------------------------------------------------------------ events
create table events (
  id         uuid primary key default uuid_generate_v4(),
  user_id    uuid not null references auth.users on delete cascade,
  project_id uuid references projects on delete set null,
  title      text not null,
  starts_at  timestamptz not null,
  ends_at    timestamptz not null,
  location   text default '',
  attendees  jsonb not null default '[]',
  notes      text default '',
  created_at timestamptz not null default now(),
  constraint events_time_order check (ends_at > starts_at)
);

create index events_user_time_idx on events (user_id, starts_at);

-- ---------------------------------------------------------- focus sessions
create table focus_sessions (
  id          uuid primary key default uuid_generate_v4(),
  user_id     uuid not null references auth.users on delete cascade,
  task_id     uuid references tasks on delete set null,
  project_id  uuid references projects on delete set null,
  label       text default '',
  planned_ms  bigint not null,
  focused_ms  bigint not null,
  ended_at    timestamptz not null default now()
);

create index focus_sessions_user_idx on focus_sessions (user_id, ended_at desc);

-- ------------------------------------------------------------------- chat
create table chat_messages (
  id         uuid primary key default uuid_generate_v4(),
  user_id    uuid not null references auth.users on delete cascade,
  role       text not null check (role in ('user', 'assistant', 'error')),
  text       text not null default '',
  actions    jsonb not null default '[]',
  created_at timestamptz not null default now()
);

create index chat_messages_user_idx on chat_messages (user_id, created_at);

-- ------------------------------------------------------------------ usage
-- One row per user per calendar month. Written only by the service role from
-- the assistant endpoint, so a client cannot reset its own counter.
create table usage_counters (
  user_id         uuid not null references auth.users on delete cascade,
  period          date not null,               -- first day of the month
  assistant_chats integer not null default 0,
  input_tokens    bigint  not null default 0,
  output_tokens   bigint  not null default 0,
  primary key (user_id, period)
);

-- ------------------------------------------------------- RLS for user data
do $$
declare t text;
begin
  foreach t in array array['projects','tasks','events','focus_sessions','chat_messages','usage_counters']
  loop
    execute format('alter table %I enable row level security', t);
    execute format(
      'create policy "own rows read" on %I for select using (auth.uid() = user_id)', t);
    execute format(
      'create policy "own rows insert" on %I for insert with check (auth.uid() = user_id)', t);
    execute format(
      'create policy "own rows update" on %I for update using (auth.uid() = user_id)', t);
    execute format(
      'create policy "own rows delete" on %I for delete using (auth.uid() = user_id)', t);
  end loop;
end $$;

-- usage_counters is readable by its owner but must never be writable by them.
drop policy "own rows insert" on usage_counters;
drop policy "own rows update" on usage_counters;
drop policy "own rows delete" on usage_counters;

-- ------------------------------------------------------------ plan limits
-- Kept in the database so the client cannot argue with them. Mirror any change
-- here in src/lib/plans.js, which exists only to render the paywall copy.
create function plan_limit(p plan_tier, resource text) returns integer
language sql immutable as $$
  select case
    when resource = 'projects' then case p when 'free' then 1 when 'plus' then 5 else null end
    when resource = 'tasks'    then case p when 'free' then 10 else null end
    when resource = 'chats'    then case p when 'free' then 0 when 'plus' then 200 else null end
  end
$$;

create function current_plan(uid uuid) returns plan_tier
language sql stable security definer set search_path = public as $$
  select coalesce(
    (select plan from profiles
      where id = uid
        -- An expired subscription silently falls back to free rather than
        -- staying paid until someone notices.
        and (plan = 'free' or plan_renews_at is null or plan_renews_at > now())),
    'free')
$$;

create function enforce_project_limit() returns trigger
language plpgsql security definer set search_path = public as $$
declare lim integer;
begin
  lim := plan_limit(current_plan(new.user_id), 'projects');
  if lim is not null and
     (select count(*) from projects where user_id = new.user_id and not archived) >= lim then
    raise exception 'plan_limit_projects' using errcode = 'check_violation';
  end if;
  return new;
end $$;

create function enforce_task_limit() returns trigger
language plpgsql security definer set search_path = public as $$
declare lim integer;
begin
  lim := plan_limit(current_plan(new.user_id), 'tasks');
  if lim is not null and
     (select count(*) from tasks where user_id = new.user_id and not done) >= lim then
    raise exception 'plan_limit_tasks' using errcode = 'check_violation';
  end if;
  return new;
end $$;

create trigger project_limit before insert on projects
  for each row execute function enforce_project_limit();

create trigger task_limit before insert on tasks
  for each row execute function enforce_task_limit();

-- Atomically claim one assistant chat. Returns false when the plan is spent,
-- so the caller never has to read-then-write and race itself.
create function claim_assistant_chat(uid uuid) returns boolean
language plpgsql security definer set search_path = public as $$
declare
  lim  integer;
  used integer;
  p    date := date_trunc('month', now())::date;
begin
  lim := plan_limit(current_plan(uid), 'chats');

  insert into usage_counters (user_id, period) values (uid, p)
    on conflict (user_id, period) do nothing;

  -- Lock this user's row so two concurrent requests cannot both pass the check.
  select assistant_chats into used from usage_counters
    where user_id = uid and period = p for update;

  if lim is not null and used >= lim then
    return false;
  end if;

  update usage_counters set assistant_chats = assistant_chats + 1
    where user_id = uid and period = p;
  return true;
end $$;

create function record_assistant_tokens(uid uuid, tin bigint, tout bigint) returns void
language plpgsql security definer set search_path = public as $$
declare p date := date_trunc('month', now())::date;
begin
  update usage_counters
     set input_tokens = input_tokens + tin, output_tokens = output_tokens + tout
   where user_id = uid and period = p;
end $$;


-- ======================================================================
-- 0002_contacts_and_invites.sql
-- ======================================================================

-- Contacts, meeting links, and a record of invites sent.
--
-- "The email on file" needs somewhere to live. Contacts are per-user and RLS'd
-- like everything else; the assistant reads them to resolve a name to an
-- address, and asks the user when it cannot.

create table contacts (
  id         uuid primary key default uuid_generate_v4(),
  user_id    uuid not null references auth.users on delete cascade,
  name       text not null,
  email      text,
  company    text default '',
  created_at timestamptz not null default now(),
  -- One row per person per user; re-saving updates rather than duplicating.
  unique (user_id, name)
);

create index contacts_user_idx on contacts (user_id);

alter table contacts enable row level security;
create policy "own rows read"   on contacts for select using (auth.uid() = user_id);
create policy "own rows insert" on contacts for insert with check (auth.uid() = user_id);
create policy "own rows update" on contacts for update using (auth.uid() = user_id);
create policy "own rows delete" on contacts for delete using (auth.uid() = user_id);

-- The user's own standing meeting room, pasted once in settings.
-- Generating a *fresh* Google Meet or Zoom link per meeting requires that
-- provider's OAuth and API; a personal room link needs neither and is what most
-- people send anyway.
alter table profiles add column meeting_link text default '';
alter table profiles add column reply_to_email text default '';

-- Audit trail. Sending mail on someone's behalf should be inspectable by them,
-- and it is the first thing to check when a recipient says nothing arrived.
create table invite_log (
  id         uuid primary key default uuid_generate_v4(),
  user_id    uuid not null references auth.users on delete cascade,
  event_id   uuid references events on delete set null,
  recipients jsonb not null default '[]',
  subject    text default '',
  provider_id text,
  status     text not null default 'sent',
  error      text,
  created_at timestamptz not null default now()
);

create index invite_log_user_idx on invite_log (user_id, created_at desc);

alter table invite_log enable row level security;
create policy "own rows read" on invite_log for select using (auth.uid() = user_id);
-- Writes come from the server (service role) only, so the log cannot be forged.


-- ======================================================================
-- 0003_sync.sql
-- ======================================================================

-- Squirrel — cross-device sync, and the hooks for external calendars.
--
-- The client stays local-first: it writes to its own storage immediately and
-- reconciles with Postgres in the background. That keeps the app instant and
-- usable on a plane, and it means the network is never in the way of typing.
-- The cost is that two devices can edit the same row while offline, so the
-- schema has to make conflicts decidable:
--
--   updated_at  every write stamps it, by trigger, so no client can forget.
--   deleted_at  deletes are tombstones. A row that simply vanished is
--               indistinguishable from a row this device has not pulled yet,
--               and the second reading resurrects it on the next sync.
--
-- Resolution is last-write-wins on updated_at. That is the right trade here:
-- the alternative is merge UI for a calendar entry, which nobody wants, and
-- the loser is recoverable because the row is still in the audit of its own
-- history. Deletes win ties — undeleting something a user deleted is worse
-- than losing an edit they can redo.

-- --------------------------------------------------------------- stamping
-- clock_timestamp(), not now(). now() is the transaction's start time and is
-- frozen for its whole life, so a batch of writes would all carry the same
-- stamp and two edits inside one transaction could not be ordered at all.
create or replace function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = clock_timestamp();
  return new;
end $$;

do $$
declare t text;
begin
  foreach t in array array['projects', 'tasks', 'events', 'focus_sessions'] loop
    execute format('alter table %I add column if not exists updated_at timestamptz not null default now()', t);
    execute format('alter table %I add column if not exists deleted_at timestamptz', t);
    execute format('drop trigger if exists %I on %I', t || '_touch', t);
    execute format(
      'create trigger %I before update on %I for each row execute function touch_updated_at()',
      t || '_touch', t);
    -- The whole sync query is "everything of mine changed since X", so that
    -- is the index. Partial on deleted_at would exclude tombstones, which are
    -- exactly what the other device needs to hear about.
    execute format('create index if not exists %I on %I (user_id, updated_at)', t || '_sync_idx', t);
  end loop;
end $$;

-- ------------------------------------------------------------ device clocks
-- One row per device per user, holding the high-water mark of what that device
-- has already pulled. Kept server-side rather than in the client so a browser
-- that clears its storage re-pulls everything instead of silently missing the
-- window it was away for.
create table sync_state (
  user_id     uuid not null references auth.users on delete cascade,
  device_id   text not null,
  pulled_at   timestamptz not null default 'epoch',
  device_name text default '',
  seen_at     timestamptz not null default now(),
  primary key (user_id, device_id)
);

alter table sync_state enable row level security;
create policy "own sync state" on sync_state for all
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ------------------------------------------------------- external calendars
-- One row per connected calendar account.
--
-- Google is reachable from a server: an OAuth refresh token is enough to write
-- to it forever, so that sync runs whether or not the app is open.
--
-- Apple is not. There is no server-side Apple Calendar API. The only supported
-- way into someone's Apple Calendar is EventKit, on their own device, from the
-- native app — so an 'apple' row here records a device that has been granted
-- calendar permission, and carries no token at all. Its sync happens on that
-- device while the app runs. See DEPLOY.md.
create type calendar_provider as enum ('google', 'apple');

create table calendar_links (
  id            uuid primary key default uuid_generate_v4(),
  user_id       uuid not null references auth.users on delete cascade,
  provider      calendar_provider not null,
  -- Google: the account's email. Apple: the device identifier.
  account       text not null,
  -- Google: the target calendar. Apple: the EventKit calendar identifier.
  calendar_id   text default '',
  calendar_name text default '',
  -- Google only, and never readable by the client — see the policies below.
  refresh_token text,
  -- Google's incremental cursor. Null forces a full resync.
  sync_token    text,
  -- Push channel, so incoming changes arrive instead of being polled for.
  channel_id      text,
  channel_expires timestamptz,
  write_back    boolean not null default true,
  last_synced_at timestamptz,
  last_error    text,
  created_at    timestamptz not null default now(),
  unique (user_id, provider, account, calendar_id)
);

create index calendar_links_user_idx on calendar_links (user_id);
-- The webhook receives a channel id and nothing else, and has to find the row.
create index calendar_links_channel_idx on calendar_links (channel_id)
  where channel_id is not null;

alter table calendar_links enable row level security;

-- Deliberately split. The client may see that a calendar is connected and may
-- disconnect it, but must never be able to read a refresh token or write one —
-- a token that leaks into a browser is a permanent grant on someone's whole
-- calendar. Reads go through the view below; the server uses the service role.
create policy "own links delete" on calendar_links for delete
  using (auth.uid() = user_id);
create policy "own links toggle" on calendar_links for update
  using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "own links read" on calendar_links for select
  using (auth.uid() = user_id);

-- The policy decides which rows; these grants decide which columns, and they
-- are what actually keeps refresh_token and sync_token out of the browser. A
-- policy can be loosened by a later migration without anyone noticing; a
-- missing column grant fails loudly.
revoke all on calendar_links from anon, authenticated;
grant select (id, user_id, provider, account, calendar_id, calendar_name,
              write_back, last_synced_at, last_error, created_at)
  on calendar_links to authenticated;
grant update (write_back) on calendar_links to authenticated;
grant delete on calendar_links to authenticated;

-- --------------------------------------------------------------- event map
-- Which of our events corresponds to which event in an external calendar.
--
-- Needed in both directions and needed to stop loops: without it, an event we
-- push to Google comes back on the next pull as a new event, which we push
-- again. `etag` lets a pull decide whether the remote copy actually changed or
-- is just our own write echoing back.
create table event_links (
  event_id    uuid not null references events on delete cascade,
  link_id     uuid not null references calendar_links on delete cascade,
  remote_id   text not null,
  etag        text,
  -- Which side last wrote, so an echo is recognisable.
  pushed_at   timestamptz,
  pulled_at   timestamptz,
  primary key (event_id, link_id),
  unique (link_id, remote_id)
);

alter table event_links enable row level security;
create policy "own event links" on event_links for all
  using (exists (select 1 from events e where e.id = event_id and e.user_id = auth.uid()))
  with check (exists (select 1 from events e where e.id = event_id and e.user_id = auth.uid()));

-- ---------------------------------------------------------------- the pull
-- Everything of mine that changed since a cursor, tombstones included.
--
-- Returned as one payload rather than four round trips, and stamped with the
-- server's clock: the cursor must come from the same clock that wrote the
-- rows, or a device whose system time runs fast skips its own changes.
--
-- The cursor is deliberately rewound. A write that started before this pull
-- but commits after it carries an updated_at earlier than the pull, yet was
-- invisible while the pull ran — take the pull's own timestamp as the next
-- cursor and that row is skipped forever. Overlapping by a window longer than
-- any sane transaction closes the hole, and re-pulling a few rows costs
-- nothing because the merge is idempotent: same row, same updated_at, no
-- change. Correctness over elegance.
create or replace function pull_changes(since timestamptz)
returns jsonb
language sql security invoker stable as $$
  select jsonb_build_object(
    'cursor', clock_timestamp() - interval '30 seconds',
    'projects', coalesce((select jsonb_agg(to_jsonb(p)) from projects p
       where p.user_id = auth.uid() and p.updated_at > since), '[]'::jsonb),
    'tasks', coalesce((select jsonb_agg(to_jsonb(t)) from tasks t
       where t.user_id = auth.uid() and t.updated_at > since), '[]'::jsonb),
    'events', coalesce((select jsonb_agg(to_jsonb(e)) from events e
       where e.user_id = auth.uid() and e.updated_at > since), '[]'::jsonb),
    'sessions', coalesce((select jsonb_agg(to_jsonb(s)) from focus_sessions s
       where s.user_id = auth.uid() and s.updated_at > since), '[]'::jsonb)
  );
$$;

grant execute on function pull_changes(timestamptz) to authenticated;

-- Tombstones are not kept forever. Ninety days is far longer than any device
-- is plausibly offline, and a device that has been away longer than that must
-- resync from scratch rather than be trusted with a stale cursor.
create or replace function purge_tombstones() returns void
language sql security definer set search_path = public as $$
  delete from projects       where deleted_at < now() - interval '90 days';
  delete from tasks          where deleted_at < now() - interval '90 days';
  delete from events         where deleted_at < now() - interval '90 days';
  delete from focus_sessions where deleted_at < now() - interval '90 days';
$$;


-- ======================================================================
-- 0004_billing.sql
-- ======================================================================

-- Recurring billing: the state a subscription needs, and a lock on it.
--
-- ## The lock, first, because it is a hole rather than a feature
--
-- `own profile update` in 0001 carries the comment "Plan and billing columns
-- are deliberately not writable here" — and does not implement it. Its check is
-- `with check (auth.uid() = id)`, which permits a signed-in user to update any
-- column on their own row, including `plan` and `plan_renews_at`. One call:
--
--     supabase.from('profiles').update({ plan: 'pro' }).eq('id', myId)
--
-- ...and the customer has Pro for nothing. Charging monthly is not worth much
-- while the thing being charged for can be granted by the person avoiding the
-- charge, so the guard goes in before any of the billing plumbing below.
--
-- Enforced with a trigger rather than a stricter policy on purpose: RLS checks
-- are per-statement conditions, easy to bypass by adding a new column later and
-- forgetting to list it. A trigger that restores the old values covers every
-- column named here regardless of what the statement asked for, and it fires
-- for every writer, including ones added after this migration.

alter table profiles
  add column if not exists billing_status   text,
  add column if not exists billing_alert    text,
  add column if not exists billing_event_at timestamptz;

comment on column profiles.billing_status is
  'Raw Stripe subscription status. The UI needs to tell "cancelled" from "card declined".';
comment on column profiles.billing_alert is
  'Set only when the customer must act. One thing for the UI to test, rather than a list of statuses to remember.';
comment on column profiles.billing_event_at is
  'event.created of the last applied billing event. Stripe does not guarantee delivery order.';

create or replace function guard_billing_columns() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  -- The webhook writes with the service role, which bypasses RLS but still
  -- fires triggers, so it has to be let through deliberately. Everything else
  -- — every end-user session — gets the billing columns put back as they were.
  if auth.uid() is null or coalesce(auth.role(), '') = 'service_role' then
    return new;
  end if;

  new.plan                   := old.plan;
  new.stripe_customer_id     := old.stripe_customer_id;
  new.stripe_subscription_id := old.stripe_subscription_id;
  new.apple_transaction_id   := old.apple_transaction_id;
  new.plan_renews_at         := old.plan_renews_at;
  new.billing_status         := old.billing_status;
  new.billing_alert          := old.billing_alert;
  new.billing_event_at       := old.billing_event_at;
  return new;
end $$;

drop trigger if exists profiles_guard_billing on profiles;
create trigger profiles_guard_billing
  before update on profiles
  for each row execute function guard_billing_columns();

-- The comment in 0001 described this intent; now something implements it.
comment on function guard_billing_columns() is
  'Reverts billing columns on any update not made by the service role. The RLS policy alone permits them.';


-- ======================================================================
-- 0005_studio_tier.sql
-- ======================================================================

-- A third tier, and the free caps that go with the pricing page.
--
-- Studio sits above Pro. It needs no new limit rows — every paid tier is
-- unlimited on projects, tasks, and chats — so the enum value is all the
-- database needs; what Studio *adds* (teammates, shared client projects) is
-- feature access, enforced where those features live, not a number here.
--
-- `add value` cannot be referenced in the same transaction it is created in, so
-- nothing below names 'studio' literally: plan_limit routes every non-free
-- tier through its `else` branch, and current_plan only ever compares against
-- 'free'. That keeps this migration safe to run as a single script.

alter type plan_tier add value if not exists 'studio';

-- Free was 1 project / 10 tasks; the pricing page now offers 2 / 15, so the
-- enforced limit has to match the promise. Plus is folded into the unlimited
-- tiers, matching src/lib/plans.js where it is an alias of Pro.
create or replace function plan_limit(p plan_tier, resource text) returns integer
language sql immutable set search_path = public as $$
  select case
    when resource = 'projects' then case when p = 'free' then 2   else null end
    when resource = 'tasks'    then case when p = 'free' then 15  else null end
    when resource = 'chats'    then case when p = 'free' then 0   else null end
    else 0
  end
$$;


-- ======================================================================
-- 0006_free_ai_taste.sql
-- ======================================================================

-- Give Free a taste of the paid model.
--
-- The built-in assistant is deterministic and runs in the browser, so it is
-- already unlimited on every tier at zero marginal cost. The metered thing is
-- the Haiku fallback in api/interpret.js — the one endpoint that costs money —
-- which only fires on the long tail the rules cannot parse.
--
-- Free was 0, which meant a free user never once saw the AND step in. That is
-- the wrong wall: the smart assist is the single best reason to upgrade, and
-- nobody upgrades for a feature they have never felt. So Free gets 25 assists a
-- month — enough to experience it and hit a wall worth paying past — while the
-- paid tiers stay unlimited, because the fallback fires so rarely that real
-- spend per paying user is a rounding error.
create or replace function plan_limit(p plan_tier, resource text) returns integer
language sql immutable set search_path = public as $$
  select case
    when resource = 'projects' then case when p = 'free' then 2   else null end
    when resource = 'tasks'    then case when p = 'free' then 15  else null end
    when resource = 'chats'    then case when p = 'free' then 25  else null end
    else 0
  end
$$;


-- ======================================================================
-- 0007_chat_sync.sql
-- ======================================================================

-- The conversation, on every device.
--
-- chat_messages has existed since 0001 and nothing has ever written to it. The
-- assistant's thread lived only in the browser that produced it, so asking
-- Squirrel something on a phone and then opening a laptop showed an empty
-- conversation — and the thread is not decoration: she resolves "move it an
-- hour later" against what was said before. A conversation that does not
-- follow you makes the pronoun mean nothing on the second device.
--
-- Same machinery as every other synced table: an updated_at the trigger keeps,
-- a deleted_at so clearing the chat propagates instead of resurrecting, and the
-- (user_id, updated_at) index the pull query actually uses.

alter table chat_messages add column if not exists updated_at timestamptz not null default now();
alter table chat_messages add column if not exists deleted_at timestamptz;

drop trigger if exists chat_messages_touch on chat_messages;
create trigger chat_messages_touch before update on chat_messages
  for each row execute function touch_updated_at();

create index if not exists chat_messages_sync_idx on chat_messages (user_id, updated_at);

-- Append-only in practice, so there is no conflict to resolve — a merge is a
-- union. The generic last-write-wins rule handles it correctly for free, since
-- a message never changes after it is written.
create or replace function pull_changes(since timestamptz)
returns jsonb
language sql security invoker stable set search_path = public as $$
  select jsonb_build_object(
    'cursor', (now() - interval '2 seconds'),
    'projects', coalesce((select jsonb_agg(to_jsonb(p)) from projects p
       where p.user_id = auth.uid() and p.updated_at > since), '[]'::jsonb),
    'tasks', coalesce((select jsonb_agg(to_jsonb(t)) from tasks t
       where t.user_id = auth.uid() and t.updated_at > since), '[]'::jsonb),
    'events', coalesce((select jsonb_agg(to_jsonb(e)) from events e
       where e.user_id = auth.uid() and e.updated_at > since), '[]'::jsonb),
    'sessions', coalesce((select jsonb_agg(to_jsonb(s)) from focus_sessions s
       where s.user_id = auth.uid() and s.updated_at > since), '[]'::jsonb),
    -- Bounded on purpose. The browser keeps the last 200 messages and a device
    -- that has been away for months does not need every one it missed — it
    -- needs the recent thread, which is all the assistant reads anyway.
    'chat', coalesce((select jsonb_agg(to_jsonb(c)) from (
       select * from chat_messages c
       where c.user_id = auth.uid() and c.updated_at > since
       order by c.created_at desc limit 200) c), '[]'::jsonb)
  )
$$;

comment on function pull_changes(timestamptz) is
  'Everything of the caller''s that changed since the given instant, including the assistant thread.';


-- ======================================================================
-- 0008_purpose.sql
-- ======================================================================

-- Purpose: a project can say why it exists.
--
-- One column, written from the helix's reading panel. Text, defaulted empty,
-- so every existing row is simply a strand whose meaning has not been written
-- down yet.
alter table projects add column if not exists meaning text not null default '';


-- ======================================================================
-- 0009_chat_ceiling.sql
-- ======================================================================

-- Every tier has a ceiling, because every chat is a model call billed to the
-- app's owner.
--
-- Pro and Studio were `null` — unlimited — which turned one enthusiastic
-- subscriber (or one scripted abuser) into an unbounded API bill. The app's
-- promise is that it never costs the owner per use: the deterministic parser
-- answers most messages for free on-device, and these ceilings only meter the
-- model-backed boost path. At current assistant pricing they cost at most a
-- few dollars of a much larger subscription, and an honest ceiling beats a
-- silent one: the client reads the same numbers from plans.js and warns as it
-- approaches.
create or replace function plan_limit(p plan_tier, resource text) returns integer
language sql immutable set search_path = public as $$
  select case
    when resource = 'projects' then case when p = 'free' then 2    else null end
    when resource = 'tasks'    then case when p = 'free' then 15   else null end
    when resource = 'chats'    then case p
                                      when 'free'   then 0
                                      when 'plus'   then 1000
                                      when 'pro'    then 1000
                                      when 'studio' then 3000
                                    end
  end
$$;


-- ======================================================================
-- 0010_lock_metering_rpcs.sql
-- ======================================================================

-- Lock the metering functions to the server, not the browser.
--
-- claim_assistant_chat and record_assistant_tokens are SECURITY DEFINER: they
-- run as the owner and write usage_counters, a table RLS otherwise makes
-- unwritable by clients. That is correct — only the server should move the
-- meter. But a SECURITY DEFINER function keeps Postgres's default EXECUTE grant
-- to PUBLIC, so the anon and authenticated roles (the keys shipped to every
-- browser) could call them directly via supabase.rpc(...):
--
--   * record_assistant_tokens(uid, tin, tout) — inflate anyone's token counter,
--     poisoning the usage numbers the owner reads to set prices.
--   * claim_assistant_chat(uid) — burn any user's monthly allowance, or (passing
--     one's own id) spend chats outside the /api/interpret path that is supposed
--     to be the only place spend happens.
--
-- The API calls both through the service-role client (asService in
-- api/_lib/db.js), which is not subject to these grants, so revoking PUBLIC
-- costs the server nothing and closes the client's back door. Belt and braces:
-- grant EXECUTE explicitly to service_role after the revoke.

revoke execute on function claim_assistant_chat(uuid) from public;
revoke execute on function record_assistant_tokens(uuid, bigint, bigint) from public;

grant execute on function claim_assistant_chat(uuid) to service_role;
grant execute on function record_assistant_tokens(uuid, bigint, bigint) to service_role;


-- ======================================================================
-- 0011_subprojects_pins_repeat.sql
-- ======================================================================

-- The four fields the planner grew, so they survive a second device.
--
-- Sub-projects, pins and repetition were added to the local store without
-- reaching this schema, which is the quiet half of that bug: everything works
-- perfectly on one machine and silently loses meaning on the next sync. A
-- branch would arrive on the iPhone with no parent, a block dragged to
-- Thursday would come back unpinned, and a weekly task would stop coming
-- back. Nothing errors — the data just isn't there.
--
-- All four are nullable with sane defaults, so every existing row keeps its
-- current behaviour: no parent, no pin, no repetition.

-- A project may grow off another project. Self-referencing, nullable, and
-- ON DELETE SET NULL rather than CASCADE: deleting a parent must not delete
-- the work filed under it. The app draws an orphaned shoot on the trunk, so
-- a null parent is a display decision, never lost work.
alter table projects
  add column if not exists parent_id uuid references projects on delete set null;

create index if not exists projects_parent_idx on projects (parent_id)
  where parent_id is not null;

alter table tasks
  -- "This one, Thursday" — the day a person placed by hand, and the minute
  -- they dropped it on. The time is meaningless without the day, which is
  -- why the planner ignores it alone; stored as plain text (HH:MM) because
  -- it is a wall-clock intention, not an instant: 9am stays 9am in a new
  -- timezone, the same rule events follow through toLocal/fromLocal.
  add column if not exists pin_day  date,
  add column if not exists pin_time text,
  -- Work that comes back. Advanced from `due` when the task is ticked off.
  add column if not exists repeat   text
    check (repeat is null or repeat in ('day', 'week', 'month'));

comment on column projects.parent_id is
  'Sub-project: the branch this one grows off. Null is a trunk branch.';
comment on column tasks.pin_day is
  'A day the person chose by hand; the router plans the rest of the week around it.';
comment on column tasks.pin_time is
  'HH:MM wall clock to start at on pin_day. Ignored without pin_day.';
comment on column tasks.repeat is
  'day | week | month. On completion the task respawns with due advanced.';


-- ======================================================================
-- 0012_organizations.sql
-- ======================================================================

-- Companies: one subscription, many people, and no window into their work.
--
-- ## What an organisation is, and deliberately is not
--
-- It is a way to *pay for* several people at once. A company buys seats, hands
-- them out by email, and every person holding one gets the paid plan. That is
-- the whole of it.
--
-- It is **not** a way to watch them. Every policy on projects, tasks, events
-- and sessions still reads `auth.uid() = user_id` and nothing here changes
-- one of them: an org admin cannot read a member's work, and no migration
-- after this one should make that possible without a very good answer to why.
--
-- That is a product decision as much as a privacy one. A planner an employer
-- can read is a planner whose users keep a second, private list — which makes
-- the tool useless for the exact planning it exists to do. "Your company pays
-- for it; your company cannot see it" is the sentence that makes this sellable
-- to the people who have to use it, and it is only true if it is true in the
-- schema.
--
-- What an admin can see is the seat: who holds one, when they joined, whether
-- they have ever signed in. Presence, not contents.

create type org_role as enum ('member', 'admin');

create table organizations (
  id                     uuid primary key default uuid_generate_v4(),
  name                   text not null,
  -- The plan every seat-holder inherits. Written only by the Stripe webhook,
  -- exactly like profiles.plan.
  plan                   plan_tier not null default 'free',
  -- Seats paid for. Membership is refused past this, so a seat-holder always
  -- has a seat rather than the company quietly over-running its subscription.
  seats                  integer not null default 0 check (seats >= 0),
  stripe_customer_id     text unique,
  stripe_subscription_id text unique,
  plan_renews_at         timestamptz,
  billing_status         text,
  billing_alert          text,
  billing_event_at       timestamptz,
  created_at             timestamptz not null default now()
);

create table org_members (
  org_id    uuid not null references organizations on delete cascade,
  user_id   uuid not null references auth.users on delete cascade,
  role      org_role not null default 'member',
  joined_at timestamptz not null default now(),
  primary key (org_id, user_id)
);

create index org_members_user_idx on org_members (user_id);

-- An invitation is addressed to an email, because the person may not have an
-- account yet — which is the ordinary case when a company rolls this out.
create table org_invites (
  id          uuid primary key default uuid_generate_v4(),
  org_id      uuid not null references organizations on delete cascade,
  email       text not null,
  role        org_role not null default 'member',
  invited_by  uuid references auth.users on delete set null,
  created_at  timestamptz not null default now(),
  accepted_at timestamptz,
  revoked_at  timestamptz
);

-- One live invitation per address per company. Re-inviting someone updates
-- rather than filling their inbox twice.
create unique index org_invites_live_idx on org_invites (org_id, lower(email))
  where accepted_at is null and revoked_at is null;
create index org_invites_email_idx on org_invites (lower(email))
  where accepted_at is null and revoked_at is null;

-- ------------------------------------------------------------- the helpers
--
-- SECURITY DEFINER on purpose. A policy on org_members that asks "is the
-- caller a member of this org" by selecting from org_members re-enters the
-- same policy and Postgres raises infinite recursion. These read the table
-- with the definer's rights, which is safe because they answer one boolean
-- about the caller and return nothing else.

create function is_org_member(org uuid, uid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (select 1 from org_members where org_id = org and user_id = uid)
$$;

create function is_org_admin(org uuid, uid uuid) returns boolean
language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from org_members
     where org_id = org and user_id = uid and role = 'admin')
$$;

-- ----------------------------------------------------------------- the plan
--
-- The single enforcement point in this schema. plan_limit, the project and
-- task triggers, and claim_assistant_chat all route through current_plan, so
-- teaching it about organisations gives every limit the same answer without
-- touching any of them.
--
-- The best of what the person holds and what any company has bought for them:
-- somebody who pays for Pro personally and sits on a company's Studio seat
-- gets Studio, and cancelling either leaves the other standing. Expiry is
-- applied on both sides — an unpaid company stops conferring anything, the
-- same way a lapsed personal subscription already did.
create or replace function current_plan(uid uuid) returns plan_tier
language sql stable security definer set search_path = public as $$
  select greatest(
    coalesce(
      (select plan from profiles
        where id = uid
          and (plan = 'free' or plan_renews_at is null or plan_renews_at > now())),
      'free'::plan_tier),
    coalesce(
      (select max(o.plan) from org_members m
         join organizations o on o.id = m.org_id
        where m.user_id = uid
          and (o.plan = 'free' or o.plan_renews_at is null or o.plan_renews_at > now())),
      'free'::plan_tier)
  )
$$;

-- ------------------------------------------------------------- seat limits
--
-- Refused rather than reconciled later. A company that adds a tenth person to
-- nine seats should be told at that moment, by the person doing the adding —
-- not have someone silently lose access at the next billing event.
create function enforce_seat_limit() returns trigger
language plpgsql security definer set search_path = public as $$
declare
  paid  integer;
  taken integer;
begin
  select seats into paid from organizations where id = new.org_id;
  select count(*) into taken from org_members where org_id = new.org_id;
  if paid is not null and taken >= paid then
    raise exception 'no seats left'
      using hint = 'Buy another seat, or remove someone first.';
  end if;
  return new;
end $$;

create trigger org_members_seat_limit before insert on org_members
  for each row execute function enforce_seat_limit();

-- ---------------------------------------------------------------------- RLS
alter table organizations enable row level security;
alter table org_members   enable row level security;
alter table org_invites   enable row level security;

-- Members see the company they belong to; only admins rename it. Billing
-- columns are the webhook's (service role), never a client's — the same
-- guard profiles carries, for the same reason.
create policy "members read org" on organizations for select
  using (is_org_member(id, auth.uid()));
create policy "admins update org" on organizations for update
  using (is_org_admin(id, auth.uid()))
  with check (is_org_admin(id, auth.uid()));

create or replace function guard_org_billing_columns() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null or coalesce(auth.role(), '') = 'service_role' then
    return new;
  end if;
  new.plan                   := old.plan;
  new.seats                  := old.seats;
  new.stripe_customer_id     := old.stripe_customer_id;
  new.stripe_subscription_id := old.stripe_subscription_id;
  new.plan_renews_at         := old.plan_renews_at;
  new.billing_status         := old.billing_status;
  new.billing_alert          := old.billing_alert;
  new.billing_event_at       := old.billing_event_at;
  return new;
end $$;

create trigger organizations_guard_billing before update on organizations
  for each row execute function guard_org_billing_columns();

-- The roster is visible to the people on it. This is presence — who holds a
-- seat — and stops there: no policy anywhere grants a colleague or an admin
-- sight of another member's projects, tasks, events or sessions.
create policy "members read roster" on org_members for select
  using (is_org_member(org_id, auth.uid()));
-- Admins hand out and take back seats; anyone may resign their own.
create policy "admins manage seats" on org_members for insert
  with check (is_org_admin(org_id, auth.uid()));
create policy "admins remove seats" on org_members for delete
  using (is_org_admin(org_id, auth.uid()) or user_id = auth.uid());
create policy "admins change roles" on org_members for update
  using (is_org_admin(org_id, auth.uid()))
  with check (is_org_admin(org_id, auth.uid()));

-- An invitation is readable by the company's admins and by the person it is
-- addressed to — who is, at that moment, very likely not a member yet.
create policy "admins read invites" on org_invites for select
  using (is_org_admin(org_id, auth.uid()) or lower(email) = lower(auth.jwt() ->> 'email'));
create policy "admins write invites" on org_invites for insert
  with check (is_org_admin(org_id, auth.uid()));
create policy "admins revoke invites" on org_invites for update
  using (is_org_admin(org_id, auth.uid()))
  with check (is_org_admin(org_id, auth.uid()));

comment on table organizations is
  'A company that buys seats. Confers a plan on its members and nothing else — no visibility into their work.';
comment on column organizations.seats is
  'Seats paid for. Membership is refused past this rather than over-running the subscription.';
comment on table org_members is
  'Who holds a seat. Presence only: no policy grants sight of another member''s data.';
